In [55]:
from bs4 import BeautifulSoup
import requests

In [56]:
url='https://www.skysports.com/premier-league-table/2019'

In [57]:
r=requests.get(url)

In [58]:
soup=BeautifulSoup(r.text,'html.parser')

In [59]:
#print(soup)

In [60]:
league_table=soup.find('table', class_='standing-table__table callfn')

In [61]:
print(league_table)

<table class="standing-table__table callfn" data-fn="table-sorter-lite" data-lite="true">
<caption class="standing-table__caption">
    Premier League 2019/20  </caption>
<colgroup class="standing-table__cols">
<col class="standing-table__cell standing-table__col1"/>
<col class="standing-table__cell standing-table__col2 standing-table__cell--name"/>
<col class="standing-table__cell standing-table__col3"/>
<col class="standing-table__cell standing-table__col4 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col5 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col6 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col7 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col8 is-hidden--bp35"/>
<col class="standing-table__cell standing-table__col9"/>
<col class="standing-table__cell standing-table__col10"/>
<col class="standing-table__cell standing-table__col11 is-hidden--bp15 is-hidden--bp35 is-hidden"/>
</colgroup>
<thead>
<tr class="standing-table__row">
<th class="standing-table__cell standing-table__header-cell" data-index="0" data-label="pos" title="Position">#</th>
<th class="standing-table__cell standing-table__header-cell standing-table__cell--name" data-index="1" title="Team">Team</th>
<th class="standing-table__cell standing-table__header-cell" data-index="2" data-label="pld" title="Played">Pl</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="3" data-label="w" title="Won">W</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="4" data-label="d">D</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="5" data-label="l">L</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="6" data-label="f">F</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp35" data-index="7" data-label="a">A</th>
<th class="standing-table__cell standing-table__header-cell" data-index="8" data-label="gd">GD</th>
<th class="standing-table__cell standing-table__header-cell" data-index="9" data-label="pts" data-sort-value="use-attribute">Pts</th>
<th class="standing-table__cell standing-table__header-cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-index="10" data-sort-value="use-attribute">Last 6</th>
</tr>
</thead>
<tbody>
<tr class="standing-table__row" data-item-id="155">
<td class="standing-table__cell">1</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Liverpool" data-short-name="Liverpool">
<a class="standing-table__cell--name-link" href="/liverpool">Liverpool</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">32</td>
<td class="standing-table__cell is-hidden--bp35">3</td>
<td class="standing-table__cell is-hidden--bp35">3</td>
<td class="standing-table__cell is-hidden--bp35">85</td>
<td class="standing-table__cell is-hidden--bp35">33</td>
<td class="standing-table__cell">52</td>
<td class="standing-table__cell" data-sort-value="1">99</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="345">
<td class="standing-table__cell">2</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Manchester City" data-short-name="Manchester City">
<a class="standing-table__cell--name-link" href="/manchester-city">Manchester City</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">26</td>
<td class="standing-table__cell is-hidden--bp35">3</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">102</td>
<td class="standing-table__cell is-hidden--bp35">35</td>
<td class="standing-table__cell">67</td>
<td class="standing-table__cell" data-sort-value="2">81</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="210">
<td class="standing-table__cell">3</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Manchester United" data-short-name="Manchester United">
<a class="standing-table__cell--name-link" href="/manchester-united">Manchester United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">18</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">66</td>
<td class="standing-table__cell is-hidden--bp35">36</td>
<td class="standing-table__cell">30</td>
<td class="standing-table__cell" data-sort-value="3">66</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="524">
<td class="standing-table__cell">4</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Chelsea" data-short-name="Chelsea">
<a class="standing-table__cell--name-link" href="/chelsea">Chelsea</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">20</td>
<td class="standing-table__cell is-hidden--bp35">6</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">69</td>
<td class="standing-table__cell is-hidden--bp35">54</td>
<td class="standing-table__cell">15</td>
<td class="standing-table__cell" data-sort-value="4">66</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row standing-table__row--divider" data-item-id="152">
<td class="standing-table__cell">5</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Leicester City" data-short-name="Leicester City">
<a class="standing-table__cell--name-link" href="/leicester-city">Leicester City</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">18</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">67</td>
<td class="standing-table__cell is-hidden--bp35">41</td>
<td class="standing-table__cell">26</td>
<td class="standing-table__cell" data-sort-value="5">62</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row standing-table__row--divider" data-item-id="608">
<td class="standing-table__cell">6</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Tottenham Hotspur" data-short-name="Tottenham Hotspur">
<a class="standing-table__cell--name-link" href="/tottenham-hotspur">Tottenham Hotspur</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">16</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">61</td>
<td class="standing-table__cell is-hidden--bp35">47</td>
<td class="standing-table__cell">14</td>
<td class="standing-table__cell" data-sort-value="6">59</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="206">
<td class="standing-table__cell">7</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Wolverhampton Wanderers" data-short-name="Wolverhampton Wanderers">
<a class="standing-table__cell--name-link" href="/wolverhampton-wanderers">Wolverhampton Wanderers</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">51</td>
<td class="standing-table__cell is-hidden--bp35">40</td>
<td class="standing-table__cell">11</td>
<td class="standing-table__cell" data-sort-value="7">59</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="413">
<td class="standing-table__cell">8</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Arsenal" data-short-name="Arsenal">
<a class="standing-table__cell--name-link" href="/arsenal">Arsenal</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">56</td>
<td class="standing-table__cell is-hidden--bp35">48</td>
<td class="standing-table__cell">8</td>
<td class="standing-table__cell" data-sort-value="8">56</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="444">
<td class="standing-table__cell">9</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Sheffield United" data-short-name="Sheffield United">
<a class="standing-table__cell--name-link" href="/sheffield-united">Sheffield United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">12</td>
<td class="standing-table__cell is-hidden--bp35">39</td>
<td class="standing-table__cell is-hidden--bp35">39</td>
<td class="standing-table__cell">0</td>
<td class="standing-table__cell" data-sort-value="9">54</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="160">
<td class="standing-table__cell">10</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Burnley" data-short-name="Burnley">
<a class="standing-table__cell--name-link" href="/burnley">Burnley</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">43</td>
<td class="standing-table__cell is-hidden--bp35">50</td>
<td class="standing-table__cell">-7</td>
<td class="standing-table__cell" data-sort-value="10">54</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="392">
<td class="standing-table__cell">11</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Southampton" data-short-name="Southampton">
<a class="standing-table__cell--name-link" href="/southampton">Southampton</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">7</td>
<td class="standing-table__cell is-hidden--bp35">16</td>
<td class="standing-table__cell is-hidden--bp35">51</td>
<td class="standing-table__cell is-hidden--bp35">60</td>
<td class="standing-table__cell">-9</td>
<td class="standing-table__cell" data-sort-value="11">52</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="229">
<td class="standing-table__cell">12</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Everton" data-short-name="Everton">
<a class="standing-table__cell--name-link" href="/everton">Everton</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">13</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">44</td>
<td class="standing-table__cell is-hidden--bp35">56</td>
<td class="standing-table__cell">-12</td>
<td class="standing-table__cell" data-sort-value="12">49</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="409">
<td class="standing-table__cell">13</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Newcastle United" data-short-name="Newcastle United">
<a class="standing-table__cell--name-link" href="/newcastle-united">Newcastle United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">16</td>
<td class="standing-table__cell is-hidden--bp35">38</td>
<td class="standing-table__cell is-hidden--bp35">58</td>
<td class="standing-table__cell">-20</td>
<td class="standing-table__cell" data-sort-value="13">44</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="234">
<td class="standing-table__cell">14</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Crystal Palace" data-short-name="Crystal Palace">
<a class="standing-table__cell--name-link" href="/crystal-palace">Crystal Palace</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">11</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">17</td>
<td class="standing-table__cell is-hidden--bp35">31</td>
<td class="standing-table__cell is-hidden--bp35">50</td>
<td class="standing-table__cell">-19</td>
<td class="standing-table__cell" data-sort-value="14">43</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="212">
<td class="standing-table__cell">15</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Brighton and Hove Albion" data-short-name="Brighton and Hove Albion">
<a class="standing-table__cell--name-link" href="/brighton-and-hove-albion">Brighton and Hove Albion</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">14</td>
<td class="standing-table__cell is-hidden--bp35">15</td>
<td class="standing-table__cell is-hidden--bp35">39</td>
<td class="standing-table__cell is-hidden--bp35">54</td>
<td class="standing-table__cell">-15</td>
<td class="standing-table__cell" data-sort-value="15">41</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="367">
<td class="standing-table__cell">16</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="West Ham United" data-short-name="West Ham United">
<a class="standing-table__cell--name-link" href="/west-ham-united">West Ham United</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">19</td>
<td class="standing-table__cell is-hidden--bp35">49</td>
<td class="standing-table__cell is-hidden--bp35">62</td>
<td class="standing-table__cell">-13</td>
<td class="standing-table__cell" data-sort-value="16">39</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="238">
<td class="standing-table__cell">17</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Aston Villa" data-short-name="Aston Villa">
<a class="standing-table__cell--name-link" href="/aston-villa">Aston Villa</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">21</td>
<td class="standing-table__cell is-hidden--bp35">41</td>
<td class="standing-table__cell is-hidden--bp35">67</td>
<td class="standing-table__cell">-26</td>
<td class="standing-table__cell" data-sort-value="17">35</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row standing-table__row--divider" data-item-id="333">
<td class="standing-table__cell">18</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Bournemouth" data-short-name="Bournemouth">
<a class="standing-table__cell--name-link" href="/bournemouth">Bournemouth</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">9</td>
<td class="standing-table__cell is-hidden--bp35">7</td>
<td class="standing-table__cell is-hidden--bp35">22</td>
<td class="standing-table__cell is-hidden--bp35">40</td>
<td class="standing-table__cell is-hidden--bp35">65</td>
<td class="standing-table__cell">-25</td>
<td class="standing-table__cell" data-sort-value="18">34</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="508">
<td class="standing-table__cell">19</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Watford" data-short-name="Watford">
<a class="standing-table__cell--name-link" href="/watford">Watford</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">8</td>
<td class="standing-table__cell is-hidden--bp35">10</td>
<td class="standing-table__cell is-hidden--bp35">20</td>
<td class="standing-table__cell is-hidden--bp35">36</td>
<td class="standing-table__cell is-hidden--bp35">64</td>
<td class="standing-table__cell">-28</td>
<td class="standing-table__cell" data-sort-value="19">34</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
<tr class="standing-table__row" data-item-id="290">
<td class="standing-table__cell">20</td>
<td class="standing-table__cell standing-table__cell--name" data-long-name="Norwich City" data-short-name="Norwich City">
<a class="standing-table__cell--name-link" href="/norwich-city">Norwich City</a>
</td>
<td class="standing-table__cell">38</td>
<td class="standing-table__cell is-hidden--bp35">5</td>
<td class="standing-table__cell is-hidden--bp35">6</td>
<td class="standing-table__cell is-hidden--bp35">27</td>
<td class="standing-table__cell is-hidden--bp35">26</td>
<td class="standing-table__cell is-hidden--bp35">75</td>
<td class="standing-table__cell">-49</td>
<td class="standing-table__cell" data-sort-value="20">21</td>
<td class="standing-table__cell is-hidden--bp15 is-hidden--bp35 is-hidden" data-sort-value="0">
</td>
</tr>
</tbody>
</table>

In [62]:
#soup.find('table')

In [63]:
import pandas as pd

In [67]:
for team in league_table.find_all('tbody'):
    rows=team.find_all('tr')
    for row in rows:
        pl_team=row.find('td', class_="standing-table__cell standing-table__cell--name").text.strip()
        #print(pl_team)
        points=row.find_all('td', class_='standing-table__cell')[2].text
        win=row.find_all('td', class_='standing-table__cell')[3].text
        #print(pl_team,points,win)

In [86]:
import pandas as pd

In [94]:
df=pd.DataFrame(pd.pl_team)

AttributeError: module 'pandas' has no attribute 'pl_team'

### 2nd Method

In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [31]:
url = 'https://www.ambitionbox.com/list-of-companies'

In [32]:
r=requests.get(url)

In [33]:
soup=BeautifulSoup(r.content,'html5lib')

In [34]:
#soup.prettify()

In [35]:
company=soup.find_all('div', class_='company-info-wrapper')

In [48]:
name=[]
rating=[]
reviews=[]
ctype=[]
for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('p').text.strip())
    reviews.append(i.find('a', class_='review-count').text.strip())
    ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())

In [51]:
df=pd.DataFrame({'name':name,'rating':rating,'reviews':reviews,'ctype':ctype})

In [52]:
df

                     name rating          reviews    ctype
0                     TCS    4.0  (22.7k Reviews)   Public
1               Accenture    4.0  (18.7k Reviews)   Public
2              ICICI Bank    4.0  (17.1k Reviews)   Public
3               Cognizant    3.8  (16.7k Reviews)  Private
4               HDFC Bank    4.0    (15k Reviews)   Public
5                   Wipro    3.8    (13k Reviews)   Public
6               Capgemini    3.7  (12.7k Reviews)   Public
7        HCL Technologies    3.8  (12.2k Reviews)   Public
8           Tech Mahindra    3.6  (11.7k Reviews)   Public
9                 Infosys    3.9  (11.7k Reviews)   Public
10          Vodafone Idea    4.2    (11k Reviews)   Public
11                Genpact    4.0  (10.9k Reviews)  Private
12              Axis Bank    3.8  (10.6k Reviews)   Public
13                    L&T    4.1  (10.5k Reviews)   Public
14           Reliance jio    4.0  (10.2k Reviews)   Public
15                    IBM    4.1    (10k Reviews)   Public
16  Concentrix Corpora...    4.1   (9.7k Reviews)   Public
17  HDB Financial Serv...    4.0   (8.6k Reviews)  Private
18                 Amazon    4.2   (8.3k Reviews)  Private
19  Kotak Mahindra Ban...    3.8     (7k Reviews)   Public
20            Tata Motors    4.1   (6.8k Reviews)   Public
21          Bharti Airtel    4.1   (6.7k Reviews)   Public
22        Teleperformance    3.6   (6.3k Reviews)  Private
23  Reliance Industrie...    4.0   (6.1k Reviews)   Public
24          Bajaj Finserv    4.1   (4.8k Reviews)   Public
25          IndusInd Bank    3.7   (4.7k Reviews)   Public
26  Mahindra & Mahindr...    4.2   (4.7k Reviews)   Public
27  Hinduja Global Sol...    3.9   (4.6k Reviews)   Public
28               Deloitte    3.9   (4.5k Reviews)  Private
29                Samsung    4.2   (4.4k Reviews)  Private